# Generated by Django 3.1.7 on 2021-04-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210410_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogheroImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('head1', models.CharField(default='', max_length=50)),
                ('para1', models.CharField(default='', max_length=50)),
                ('blogheroimage', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
