# Generated by Django 3.1.7 on 2021-04-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogheroimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogheroImage',
        ),
    ]
